name: Metrics

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ISO_METRICS }}
          filename: metrics.plugin.isocalendar.fullyear.svg

          base: ""

          # ISO calendar plugin (heatmap for full year)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
