name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: 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
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_languages: yes
          config_timezone: Asia/Dhaka
